services:
    laravel.test:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            DD_AGENT_HOST: datadog-agent
            DD_ENV: prod
            DD_TRACE_CLI_ENABLED: true
            DD_SERVICE: 'laravel'
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            DD_TRACE_REMOVE_AUTOINSTRUMENTATION_ORPHANS: true
            SUPERVISOR_PHP_COMMAND: "/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=swoole --host=0.0.0.0 --port=80"
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        links:
            - "datadog-agent:datadog-agent"
        depends_on:
            - mysql
            - datadog-agent
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    datadog-agent:
        image: datadog/agent:latest
        container_name: datadog-agent
        environment:
            #DD_HOSTNAME: COMP-NL79WWM69R
            DD_API_KEY: ${DATADOG_API_KEY}
            DD_SITE: datadoghq.eu
            DD_LOGS_ENABLED: true
            DD_LOG_LEVEL: debug
            DD_CONTAINER_EXCLUDE_LOGS: name:datadog-agent
            DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: true
            DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /proc/:/host/proc/:ro
            - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
